CREATE TABLE [dbo].[Pacientes]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Name] NVARCHAR(50) NOT NULL, 
    [CreatedDate] DATETIME2 NULL, 
    [UpdatedDate] DATETIME2 NULL, 
    [ClinicaId] UNIQUEIDENTIFIER NULL,
    FOREIGN KEY (ClinicaId) REFERENCES Clinicas(Id) ON DELETE CASCADE
)
